<?php
class CustomException extends Exception {
  // function __construct(){
  //   parent::__construct();
  //  }
  // public function errorMessage() {
  //   //error message
  //   $errorMsg = 'Error on line '.$this->getLine().' in '.$this->getFile().': <b>'.$this->getMessage();
  //   return $errorMsg;
  // }
  // public function Array_Message() {
  //   $result=array();
  //   //$errorMsg = 'Error on line '.$this->getLine().' in '.$this->getFile().': <b>'.$this->getMessage();
  //   $result['File']='Error on file-> '.$this->getFile().'on Line'.$this->getLine()."<br>";
  //   $result['Message']='Error on file-> '.$this->getMessage();
  //   $result['Error']='برنامه با مشکل مواجه شده است';
  //   $result['error']='برنامه با مشکل مواجه شده است';
    
  //   die();
  //   // return $result;
  // }
}
?>